// libs
import { Children } from 'react'
import Head from 'next/head'

// config
import { App } from 'config/app'

function Page({ children }: Children) {
  return (
    <>
      <Head>
        <title>Some Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <App>{children}</App>
      </main>
    </>
  )
}

export { Page }
